build:
    environment:
        php: 8.1
    tests:
        override:
            - php-scrutinizer-run

filter:
    excluded_paths:
        - bin/
        - config/
        - public/
        - src/DataFixtures/
        - src/Kernel.php
        - tests/
        - var/
    dependency_paths:
        - vendor/

checks:
    php: true

tools:
    external_code_coverage:
        timeout: 600
        runs: 2
