language: php

php:
    - 8.1

env:
    global:
        - XDEBUG_MODE=coverage

install:
    - composer --optimize-autoloader --no-interaction install

script:
    - ./bin/phpunit --coverage-clover=coverage.clover
    - composer global require scrutinizer/ocular:^1.9
    - php ~/.config/composer/vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
